mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 256
    batch: {}

  exporters:
    otlphttp:
      endpoint: "https://mtn-sre-assessment-observability-fece91.apm.us-central1.gcp.elastic.cloud:443"
      headers:
        Authorization: "ApiKey VTA3MEY1MEJOY1NvalI1MFkyWEY6RU1DTXk5RmNXSS13MWFyMVlKbTRnUQ=="

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp]

      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp]

      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp]
