apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: gcr.io/google-samples/microservices-demo/paymentservice:v0.4.0
          ports:
            - containerPort: 50051
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-agent:4317
            - name: OTEL_SERVICE_NAME
              value: paymentservice